// Generated by dia2code
#ifndef STATE__CAPACITY__H
#define STATE__CAPACITY__H


namespace state {

  /// class Capacity - 
  class Capacity {
    // Attributes
  public:
     ;
     ;
    // Setters and Getters
  };

};

#endif
