// Generated by dia2code
#ifndef STATE__CHARACTERSTATUS__H
#define STATE__CHARACTERSTATUS__H


namespace state {

  /// class CharacterStatus - 
  class CharacterStatus {
    // Attributes
  private:
    bool mIsAlive;
    bool mIsSelected;
    bool mIsPlayable;
    // Setters and Getters
  };

};

#endif
