// Generated by dia2code
#ifndef STATE__COMBATSTATUS__H
#define STATE__COMBATSTATUS__H


namespace state {

  enum CombatStatus {
    PLAYER_TURN     = 0,
    IA_TURN     = 1,
    IN_COMBAT     = 2,
    OUT_COMBAT     = 3
  };

};

#endif
