// Generated by dia2code
#ifndef STATE__FINALBOSS__H
#define STATE__FINALBOSS__H


namespace state {
  class Character;
}

#include "Character.h"

namespace state {

  /// class FinalBoss - 
  class FinalBoss : public state::Character {
    // Setters and Getters
  };

};

#endif
