name: C/C++ CI

on:
  push:
    branches: [ action-test ]
  pull_request:
    branches: [ action-test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install lcov
      run: apt-install lcov
    
    - name: make
      run: make


